spring:
  application:
    name: scheduling-ThreadPoolTaskScheduler
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    sampleTaskStart:
      enabled: true
    sampleTaskCancel:
      enabled: true
    sampleTaskCheckPeriodicRunning:
      enabled: true

scheduler:
  task:
    scheduling:
      cron: "*/5 * * * * *"
